### PR TITLE
Update to version 0.5.5

### PR DESCRIPTION
**Pull request by windelbouwman**

### CODE REVIEW

**Comment by almarklein** [comment]
I suspect this is a glitch in conda or something, maybe [this](https://github.com/conda/conda/issues/6527), a solution is proposed there.

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by windelbouwman** [comment]
Wow, @isuruf you can request a re-render like that?

**Comment by almarklein** [comment]
Does that invoke a bot, or is at prayer to the conda-forge gods?

**Comment by isuruf** [comment]
> Does that invoke a bot, or is at prayer to the conda-forge gods?

It does invoke a bot, https://conda-forge.org/docs/webservice.html

**Pull request merged**
